
FROM node:18

#Définir le répertoire de travail pour ce conteneur
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
# Copie le reste des fichiers du projet
COPY . ./
EXPOSE 8080
CMD ["npm", "start"]
