FROM node:18

#Répertoire de travail dans le conteneur
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
RUN npm install -g nodemon
# Copie le reste des fichiers du projet
COPY . ./
EXPOSE 3000
CMD ["npm", "start"]
